nodes:
    $for(params.sources, source):
        convert_$item(source.name):
            shell:
                command: custom_charuco to-underfolder {input} --dest {output} --fps {fps}
                inputs:
                    input: $item(source.path)
                    fps: $var(params.convert.fps, default=1)
                outputs:
                    output: $tmp()/images/$item(source.name)

        add_board_$item(source.name):
            pipe:
                operations:
                    map:
                        stage:
                            add_charuco_boards:
                                base_board: $var(params.add_boards.base_board)
                                n_boards: $var(params.add_boards.n_boards)
                input: $tmp()/images/$item(source.name)
                output: $tmp()/with_boards/$item(source.name)

    calibrate:
        pipe:
            input: $tmp()/with_boards/calibration
            output: $tmp()/with_calibration/calibration
            operations:
                - calibrate:
                      board_key: $var(params.calibrate.board_key)

    transfer_calibration:
        transfer_root_item:
            input: $tmp()/with_boards/dataset
            target: $tmp()/with_calibration/calibration
            output: $tmp()/with_calibration/dataset
            target_keys:
                - camera

    detect:
        pipe:
            input: $tmp()/with_calibration/dataset
            output: $tmp()/with_detections
            operations:
                map:
                    stage:
                        multi_board_detect_1:
                            debug: $var(params.detect.debug, default=False)

    compute_poses:
        pipe:
            input: $tmp()/with_detections
            output: $var(params.output)
            operations:
                - filter_nan:
                      key: poses
                - merge_detections:
                      refiner: $var(params.compute_poses.refiner)
                - filter_nan:
                      key: pose
                - map:
                      stage:
                          filter-keys:
                              key_list:
                                  - image
                                  - pose
                                  - camera
